### ISSUE TITLE
Update default branch to main instead of master

### ISSUE THREAD

**Issue by mikemhenry** [MolSSI/cookiecutter-cms#155]
Related: https://github.com/MolSSI/cookiecutter-cms/pull/137

We should make the default branch `main` in this repository, as well as repositories created with the cookie cutter.

**Comment by ijpulidos** [comment]
I was trying to understand where the decision of making the default branch as `main` or `master` is taken. Do you know where this takes place? I was checking the cookiecutter cli but it doesn't seem to allow the option. Maybe this is an issue that we should raise upstream. It would be helpful to have an option to specify the main branch (hopefully defaulting to `main`).

**Comment by janash** [comment]
I agree with updating this branch name to `main`. 

@ijpulidos - your default branch will depend on your local git configuration. You can set your default branch in your git configuration using

```
git config --global init.defaultBranch main
```

We could add the option to do main or master to the cookiecutter, but it would probably be best just to do a branch rename after the `git init` command, ie - `git branch -M main`. This would rename the branch even someone didn't have their default branch name configured. 

@Lnaden  - since we're updating the cookiecutter now, something to include?

**Comment by Lnaden** [comment]
This was fixed with #157 and I have changed the main repo's default branch as well.
